function main_age_depth_plot(Age_p1, Age_p5, Age_mean, div_age, flank_age, ...
                          Age_p1_basal_melt_20mmyr, Age_p1_basal_melt_10mmyr, ...
                          AgeData, DepthData, known_ages, irh_err_d, irh_err, ...
                          H, z, Hmin, pinks, blues, greens)
    % main plot
    figure; hold all;
    [div, flank, h, basal10, basal, bed, oldest, hdata, irhs] = plot_age_depth_profiles(...
        Age_p1, Age_p5, Age_mean, div_age, flank_age, ...
        Age_p1_basal_melt_20mmyr, Age_p1_basal_melt_10mmyr, ...
        AgeData, DepthData, known_ages, irh_err_d, irh_err, ...
        H, z, Hmin, pinks, blues, greens);
    xlabel('Age (ka)');
    ylabel('Depth (m)');
    ylim([-50, 1400]);
    xlim([-1, 50]);
    set(gca, 'Ydir', 'reverse', 'FontSize', 14);
    box on; 
    grid on;
    legend([div; flank; h; basal10; basal; bed; oldest; hdata; irhs], ...
           'Forward model: divide flow', 'Forward model: flank flow', ...
           'Optimised model (1\leqp\leq5)', 'Basal melt = 10 mm/yr', 'Basal melt = 20 mm/yr', ...
           'Ice Thickness', 'Oldest Ice', 'Ice core data', 'IRHs', ...
           'Orientation', 'horizontal', 'fontsize', 12, 'NumColumns', 3);
    
    % inset 1 - highlighting ice core data 
    inset1 = axes('Position', [.22, .57, .17, .27]); hold on; box on;
    plot_age_depth_profiles(...
        Age_p1, Age_p5, Age_mean, div_age, flank_age, ...
        Age_p1_basal_melt_20mmyr, Age_p1_basal_melt_10mmyr, ...
        AgeData, DepthData, known_ages, irh_err_d, irh_err, ...
        H, z, Hmin, pinks, blues, greens);
    xlabel('Age (ka)');
    ylabel('Depth (m)');
    ylim([0, 140]);
    xlim([0, 0.35]);
    set(gca, 'Ydir', 'reverse', 'FontSize', 14);
    box on; 
    grid on;
   
    
    % inset 2 - highlighting IRH data
    inset2 = axes('Position', [.44, .445, .18, .267]); hold on; box on;
     plot_age_depth_profiles(...
        Age_p1, Age_p5, Age_mean, div_age, flank_age, ...
        Age_p1_basal_melt_20mmyr, Age_p1_basal_melt_10mmyr, ...
        AgeData, DepthData, known_ages, irh_err_d, irh_err, ...
        H, z, Hmin, pinks, blues, greens);
    xlabel('Age (ka)');
    ylabel('Depth (m)');
    ylim([440, 950]);
    xlim([1.8, 5.2]);
    set(gca, 'Ydir', 'reverse', 'FontSize', 14);
    box on; 
    grid on;
end